---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-role-cobalt-strike
      ansible.builtin.include_role:
        name: ansible-role-cobalt-strike
      vars:
        cobalt_strike_bucket_name: >-
          {{ lookup('amazon.aws.ssm_parameter', '/third_party_bucket_name') }}
