---
# This molecule configuration file is suitable for testing Ansible
# roles that _do not_ require SystemD.  If your Ansible role _does_
# require SystemD then you should use molecule-with-systemd.yml
# instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # The latest version of CobaltStrike requires glibc 2.29, which is
  # unavailable for Debian Buster.  When one attempts to start the
  # teamserver on Buster one gets the following output:
  #
  # root@debian10:/# cd /opt/cobaltstrike/
  # root@debian10:/opt/cobaltstrike# ./teamserver
  #
  # [*] Checking TeamServerImage for local update
  #
  # [*] Verifying MD5 Message Digest for TeamServerImage
  # TeamServerImage: OK
  #
  # [*] Will use existing X509 certificate and keystore (for SSL)
  #
  # [*] Starting teamserver
  # ./TeamServerImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./TeamServerImage)
  #
  # - image: debian:buster-slim
  #   name: debian10
  #   platform: amd64
  - image: debian:bullseye-slim
    name: debian11
    platform: amd64
  - image: debian:bookworm-slim
    name: debian12
    platform: amd64
  - image: kalilinux/kali-rolling
    name: kali
    platform: amd64
  - image: ubuntu:focal
    name: ubuntu20
    platform: amd64
  - image: ubuntu:jammy
    name: ubuntu22
    platform: amd64
scenario:
  name: default
verifier:
  name: testinfra
