---
# This molecule configuration file is suitable for testing Ansible
# roles that _do_ require SystemD.  If your Ansible role _does not_
# require SystemD then you should use molecule-no-systemd.yml instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-amazonlinux2-ansible:latest
    name: amazonlinux2-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-debian9-ansible:latest
    name: debian9-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-debian10-ansible:latest
    name: debian10-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-debian11-ansible:latest
    name: debian11-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: cisagov/docker-debian12-ansible:latest
    name: debian12-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: cisagov/docker-kali-ansible:latest
    name: kali-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora35-ansible:latest
    name: fedora35-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora36-ansible:latest
    name: fedora36-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-fedora37-ansible:latest
    name: fedora37-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    name: ubuntu-18-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    name: ubuntu-20-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    name: ubuntu-22-systemd
    platform: amd64
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  inventory:
    host_vars:
      debian9-systemd:
        # auto_legacy is still the default behavior until Ansible 2.12
        # is released, but Molecule overrides this and forces the use
        # of auto.
        #
        # In auto_legacy mode Ansible will prefer the /usr/bin/python
        # interpreter if it exists, while in auto mode it will prefer
        # the Python interpreter specified in an internal map.  In
        # most cases we only have Python3 installed, and the internal
        # map specifies /usr/bin/python3, so it is immaterial whether
        # we use auto_legacy or auto.
        #
        # The one place where it _does_ matter is our Debian9 AKA CyHy
        # instances.  Here the /usr/bin/python _and_ /usr/bin/python3
        # interpreters are both installed.  In Ansible 2.10 a Debian
        # entry was added to the internal map, so now auto_legacy
        # selects the /usr/bin/python interpreter while auto selects
        # the /usr/bin/python3 interpreter.  We want to maintain the
        # auto_legacy behavior in this case since CyHy is still
        # Python2.
        #
        # See:
        # * https://github.com/ansible-community/molecule/blob/3.0.8/molecule/provisioner/ansible.py#L389
        # * https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html#interpreter-discovery
        # * https://github.com/ansible/ansible/blob/v2.10.1/lib/ansible/config/base.yml#L1492-L1542
        # * https://github.com/ansible/ansible/blob/v2.10.1/lib/ansible/executor/interpreter_discovery.py
        ansible_python_interpreter: auto_legacy
scenario:
  name: default
verifier:
  name: testinfra
