---
# This molecule configuration file is suitable for testing Ansible
# roles that _do not_ require SystemD.  If your Ansible role _does_
# require SystemD then you should use molecule-with-systemd.yml
# instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - image: amazonlinux:2023
    name: amazonlinux2023
    platform: amd64
  - image: debian:buster-slim
    name: debian10
    platform: amd64
  - image: debian:bullseye-slim
    name: debian11
    platform: amd64
  - image: debian:bookworm-slim
    name: debian12
    platform: amd64
  - image: kalilinux/kali-rolling
    name: kali
    platform: amd64
  - image: fedora:36
    name: fedora36
    platform: amd64
  - image: fedora:37
    name: fedora37
    platform: amd64
  - image: ubuntu:bionic
    name: ubuntu18
    platform: amd64
  - image: ubuntu:focal
    name: ubuntu20
    platform: amd64
  - image: ubuntu:jammy
    name: ubuntu22
    platform: amd64
scenario:
  name: default
verifier:
  name: testinfra
