---
# This is necessary to ensure a version of this collection that is
# compatible with version 2.32.0+ of the Python requests library. This
# should be removed when it is no longer required per
# https://github.com/cisagov/skeleton-ansible-role/issues/195
collections:
  - name: community.docker
    version: ">=3.10.2"

roles:
  - name: debian_archive
    src: https://github.com/cisagov/ansible-role-debian-archive
  - name: upgrade
    src: https://github.com/cisagov/ansible-role-upgrade
