---
- hosts: all
  name: Upgrade base image
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Upgrade system packages
      ansible.builtin.include_role:
        name: upgrade
